### ISSUE TITLE
Polish errors with no useful message

### ISSUE THREAD

**Issue by monicabritton** [PacificBiosciences/IsoSeq3#11]
I have run IsoSeq3 through clustering and everything seems OK.  In the polishing step, I get lists of INFO errors(?) like:

>|> 20180717 01:33:25.441 -|- INFO       -|- Polish -|- 0x7f9671ff0700|| -|- negative inf in mutation testing: 'm54048_180711_205609/68747535/12974_15897'
>|> 20180717 01:34:28.500 -|- INFO       -|- Polish -|- 0x7f96767f9700|| -|- negative inf in mutation testing: 'm54048_180711_205609/22937830/90163_93035'

They don't seem to prevent the run from completing, but I can't find any explanation of what they mean or whether I need to take action.  I am running polish --version "tango 0.7.1 (commit v0.4.0-121-g22a3096*)"

Am I missing something?

Thanks in advance.

**Comment by armintoepfer** [comment]
They are infos that will be suppressed in the next version. If something fails, there will be warnings, errors, or fatal messages. Those infos are caused by the underlying multi molecule consensus algo. Don't worry about them ;)
