### ISSUE TITLE
Fewer transcripts in IsoSeq3 results

### ISSUE THREAD

**Issue by fantastycrane** [PacificBiosciences/IsoSeq3#13]
I encountered the similar situation in #9  when using IsoSeq3. Number of output sequences are rather small after running ccs, lima and cluster. Results from four sequenced samples are shown below.

number of cell | ccs | lima output | flnc | cluster output
-- | -- | -- | -- | --
two Sequel cells | 657596 | 377730 | 374075 | 21963
one Sequel cell | 477726 | 339985 | 335901 | 24446
eight RSII cells | 776341 | 376000 | 374706 | 20564
five RSII cells | 431389 | 103764 | 102718 | 4745

I have double checked that there was nothing wrong with primers (recommended Clontech primer were used in the experiments). And following commands were executed.
1. ccs --minPasses 0 --maxDropFraction 0.8 --minPredictedAccuracy 0.8
2. isoseq3 lima ccs.bam primers.fasta demux.ccs.bam --isoseq
3. isoseq3 cluster lima_combined.consensusreadset.xml unpolished.bam --split-bam 12
The first two steps, ccs and lima, were run in parallel and combined lima output was used to run cluster.

It has been stated in FAQ that fewer transcripts are produced with IsoSeq3 compared to IsoSeq1/2. But how much fewer can be considered reasonable? Are the numbers in my results normal?

**Comment by armintoepfer** [comment]
1) IsoSeq3 only works with full-length transcripts, thus `lima` will remove plenty of non full-length transcripts that have less than 1 pass. You can study the *.lima.summary files to get a feeling for that.
2) Fewer transcript than what? Did you run an older IsoSeq workflow or a different algorithm to compare against or is it a gut feeling? 20k full-length transcripts are very reasonable!

**Comment by fantastycrane** [comment]
Hi @armintoepfer ,

Thanks for the reply.

I have run IsoSeq2 on the last case with five RSII cells. Clustering output 83334 consensus isoforms and 8851 HQ isoforms were obtained after polishing. Over 70k reads were classified into LQ isoforms because of only having one full-length transcript covered.
The other three cases did not get cluster results with IsoSeq1 or IsoSeq2 due do large cluster (>100k reads) generated at precluster step. It stuck at iceiterative and I could not get it through. However, collapsing using HQ isoforms and corrected LQ isoforms could produce more than 30k unique isoforms with around one million ZMWs (1~2 Sequel cells or 5~8 RSII cells) according to previous projects using IsoSeq1 or IsoSeq2.

**Comment by armintoepfer** [comment]
There are many factors that play into getting fewer final transcripts for the five RSII cells, but internal benchmarks and beta customer feedback point, similarly to your experience, to the same conclusion: there are fewer but longer transcripts that reconstruct more known splice sites. Our spike-in controls even show a higher recovery rate. If I were you, I'd forget about the old results and focus on the latest version.

**Comment by fantastycrane** [comment]
Got it! Thanks.
