### ISSUE TITLE
reduce minium full_length_coverage

### ISSUE THREAD

**Issue by jayceejiao** [PacificBiosciences/IsoSeq3#15]
Hi,

I am using IsoSeq3 to process 2 cells of ISO-Seq reads from a plant species. I finished all the steps in the README file. Finally, I got 50k hq and 1k lq transcripts. I noticed that the results only include isoform supported by at least 2 full-length transcripts. After using Cupcake ToFU, I only got ~8k genes, 36k isoforms. I used to use IsoSeq_SA3nUP, and after collapsing step, it will give me much more genes. So I want to reduce the cutoff for full_length_coverage (set to 1), and redo the analysis. Can you tell me how to change this parameter? I want to capture most of the genes using ISO-Seq, do I need more sequencing?

Thanks!

Chen

**Comment by Magdoll** [comment]
Hi @jayceejiao ,

As you already know, Iso-Seq3 currently does not output FL=1 isoforms. We may consider adding them in future releases, but right now there is no way to output them.

--Liz
