### ISSUE TITLE
pbtranscript2 ?

### ISSUE THREAD

**Issue by hmyh1202** [PacificBiosciences/IsoSeq3#2]
Hi,
  I have download the latest version of smrtlink (v 5.1.0.26412) and I found that a new file named pbtranscript2 in the directory of smrtlink_5.1.0.26412/smrtcmds/bin/.

What is the different between the pbtranscript and pbtranscript2 ?  Besides, no details about the pbtranscript was provided. So I dont know how to use the pbtranscript2 to do cluster.

Thanks!

**Comment by armintoepfer** [comment]
Hi!

This repository is about the binary release of IsoSeq3 from the upcoming smrtlink v6.0.
For questions regarding current software pbtranscript and pbtranscript2, please contact your local FAS or official pacbio tech support.

Thank you for understanding!
