### ISSUE TITLE
Why isoseq3 polished HQ fasta number did not uniform?

### ISSUE THREAD

**Issue by hmyh1202** [PacificBiosciences/IsoSeq3#5]
Hi, all:
I had run isoseq3 cluster with --split-bam (test I) and without--split-bam (test II). Ang then run the isoseq3 polish, however the number of the transcript in polished.hq.fasta.gz was not uniform. The transcript  number is much more than that of test I. So why ?

**Comment by hmyh1202** [comment]
![default](https://user-images.githubusercontent.com/18067365/40692879-e08e1efc-63e6-11e8-8da9-c16fad683209.png)
And the number of polished.lq.fasta.gz is not continuous.

**Comment by armintoepfer** [comment]
1) In our tests, the number of of polished outputs is identical between split and unsplit. Please provide a simple example, if possible.
2) Did you check if transcript/44-45 are in HQ?

**Comment by hmyh1202** [comment]
OK  I will try it again in few hours! 
Thank U !

**Comment by hmyh1202** [comment]
sorry, I had been corrrect!

**Comment by armintoepfer** [comment]
You were correct? I don't understand
