### ISSUE TITLE
Issues with polish

### ISSUE THREAD

**Issue by attrna** [PacificBiosciences/IsoSeq3#6]
Hi!

I'm trying to walk through the isoseq3 pipeline. And on the polish step, I get empty fastq/fasta files. 

Here is my pipeline:
1. ccs m*.subreads.bam ccs.bam --noPolish --minPasses 1 --numThreads 16

2. lima ccs.bam primer.fasta demux.ccs.bam --isoseq --no-pbi --dump-clips --min-passes 1 --min-length 100 --chunk-size 20 --num-threads 16

3. isoseq3 cluster demux.ccs.pr_5p--pr_3p.bam unpolished.bam -j 16 --split-bam 24

and for all splitted files I run
4. isoseq3 polish $file m*.subreads.bam ${file/unpolished/polished}.bam -j 8 -v;
 
There was no warning messages and errors. Also, polished.*.transcriptset.xml and polished.*.bam are not empty but do not contain any sequences. It does not show an additional info (with -v or --logFile or --log-level INFO options) only prints "0^M0" in the log for each file.

What could cause the problem? How to solve it?

Thank you!
Anastasia

**Comment by armintoepfer** [comment]
Would you be willing to share an example privately to reproduce?

**Comment by hmyh1202** [comment]
In my polish log file, a error had been reported：
>|> 20180711 17:18:10.953 -|- ERROR      -|- ConsensusQualities -|- 0x2b9ba13af700|| -|- In Polish::ConsensusQualities(ai): negative inf in mutation testing: 'm54172_180419_112009/49676773/3858_7331'
However, isoSeq3 polish had finished.

**Comment by ylipacbio** [comment]
This is a debug information from Arrow, not a real runtime error, please  ignore the message.

**Comment by armintoepfer** [comment]
Anastasia sent me data to reproduce, I'll debug her case and then report back here.

**Comment by attrna** [comment]
Armin, thank you so much for your help! I did not have the .pbi index of my *subread.bam, so a simple "pbindex m*.subreads.bam" solved it. Everything works great now.

Thank you!
Anastasia

**Comment by armintoepfer** [comment]
Great! The new isoseq3 version will warn you if there is no `.pbi` file present!
