### ISSUE TITLE
isoseq3 cluster parameters

### ISSUE THREAD

**Issue by HenrivdGeest** [PacificBiosciences/IsoSeq3#7]
I successfully run the isoseq3 pipeline, thanks for supplying this to the community. I am also quite happy with the performance of isoseq3. Its much faster and also seems to do a much better job in the determination of the FLNC transcripts.

However, for the clustering phase I am looking for some options.
first, is is possible to set the minimum amount of reads required per cluster? I sometimes see CCS reads with a intron retention event, but after the clustering this transcript is missing.
In the image below you see two alignment tracks, the top one are the ccs reads, the bottom one is the FLNC clustering output from 'isoseq3 cluster'. You can see that there are reads with an extra intron, which are missing in the bottom track. For what I can see is that there are 2 reads required per transcript. However, I would like to set that to 1. ( it can also be that these reads are not classified as a FLNC, but that part I did not checked in depth)

![image](https://user-images.githubusercontent.com/2330901/42558969-0371effc-84f3-11e8-8f5d-0d545a80be0b.png)

Second I am looking for the setting for requiring the poly-A tail. Is that implemented somewhere?.

Third, is it possible to just remove the poly-A tailes from the FLNC (*ccs.demux.primer_5p--primer_3p*") reads and output the reads without the clustering?

**Comment by armintoepfer** [comment]
Hi!

1) It is strange to see that one read with an extra intron, should not happen...would you be willing to share a slice of your data privately for enhancements?
2) Currently, you can't set the minimum requirement to 1, since I don't trust a single read. But that might be a future optional feature.
3) The polyA tail requirement is already included in an internal version that we haven't pushed publicly yet. But that will happen very soon.
4) Also in the next version. `isoseq3 cluster` will create an `unpolished.flnc.bam` after concatemer removal and polyA trimming.

**Comment by HenrivdGeest** [comment]
Thanks for your reply. 
1. Why is it so strange to see that there are transcripts with introns? If you mean the one in the second track, it might be because there are multiple ccs reads having this intron. (the top track is not fully shown)
2. I see why you would not trust a single read, but for my purposes it would be great to keep them.
3. it seems that when I run isoseq3 cluster with  "--no-consensus --no-consensus-merge" as parameters, is does not cluster the reads, but does trim them. Or am I wrong here?
4 . I think I already see that file. Maybe that feature is already in the source code release? (there is no isoseq3 binary release, just the source code which I used)

**Comment by armintoepfer** [comment]
1. When we talk about extra intron, is one example in the second read in your plot?
2. We are considering adding it to a future version.
3. Both parameters are solely for debugging purposes and might vanish from the CLI ;)
4. What source code release? I didn't upload any source.

**Comment by armintoepfer** [comment]
Without data, we can't reproduce/debug your observation. If you are willing to share data with us privately, please let us know.

**Comment by armintoepfer** [comment]
Will close until it's reproducible by us.
