### ISSUE TITLE
filter ccs.bam on predicted accuracy?

### ISSUE THREAD

**Issue by HenrivdGeest** [PacificBiosciences/IsoSeq3#8]
With the old isoseq the bam had a tag which could be used for filtering on accuracy:
-tag "rq:>0.999" 
In the Isoseq3 ccs.bam I do not see such a tag. There is a tag for the number of subreads(=passes) for each read "np:i", but not a accuracy tag.
Is it still possible to filter on this tag?
I am asking this because in that way I can run the ccs creation once, with numpasses=1. For any other analysis later I could filter the ccs output. Currently I run the ccs part multiple times, which is quite expensive.

**Comment by armintoepfer** [comment]
This is because we do not polish ccs reads in our workflow. Feel free to run ccs the way you want and then either use datasets to filter on the `rq` tag or wait until I implemented the rq-filter in `isoseq3 cluster`.

**Comment by armintoepfer** [comment]
After consideration, please use our lightweight dataset filters. If you don't have SMRTLink installed

```
conda install pbcoretools
````

And then filter based on the consensusreadset.xml (implicitly using the pbi):

```
dataset filter ccs.consensusreadset.xml ccs.filtered.consensusreadset.xml "rq>0.999"
```

Which adds following block to the xml:

```
	<pbds:Filters>
		<pbds:Filter>
			<pbbase:Properties>
				<pbbase:Property Name="rq" Operator="&gt;" Value="0.999"/>
			</pbbase:Properties>
		</pbds:Filter>
	</pbds:Filters>
```

This file can be used as input for `isoseq3`, which respects dataset filters.
Keep in mind, predicted accuracy is stored as a float.

Let me know if that does not work. I'll close it for now, but will be informed by mail if you comment.
