### ISSUE TITLE
Is Isoseq3 compatible with RS II data

### ISSUE THREAD

**Issue by agraubert** [PacificBiosciences/IsoSeq3#9]
I am working with samples sequenced on RS II.  My original pipeline used Isoseq2 and a modified version of Isoaux to generate final isoform annotations.  Since the beta release I've started experimenting with Isoseq3 on my data but I'm getting vastly fewer reads than before. 

For example, in one sample (25,063 reads in CCS bam), `pbtranscript classify` yielded 9,418 sequences and `pbtranscript cluster` reduced this to 516 unique transcripts. However, in Isoseq3, `lima` produces 109 sequences and `isoseq3 cluster` further reduces that to 3 unique transcripts .

I'm wondering if RS II simply doesn't meet the throughput requirements for `lima` to produce ample output, or if there are simply parameters in the new pipeline that I'm not using correctly.

Thanks!

**Comment by armintoepfer** [comment]
Let's investigate step by step.
Would you mind posting the summary file of lima and the barcode.fasts file?

**Comment by agraubert** [comment]
Here are the requested files

[output.lima.summary](https://github.com/PacificBiosciences/IsoSeq3/files/2194301/output.lima.summary.txt)
[primers.fasta](https://github.com/PacificBiosciences/IsoSeq3/files/2194303/primers.fasta.txt)

After glancing through the summary file, it seems like the vast majority of reads are filtered out for having 5'/5' or 3'/3' primer pairs. Is it possible that this is an error with the primers I provided to lima?

**Comment by armintoepfer** [comment]
The old isoseq classify was too permissive and would not have removed primer pairs only because the overhang was missing.

Let's see:
1. Did you run lima with `--isoseq`?
2. Did you run ccs with `--minPasses` above 0?
3. Were the primers from the file actually used in your library?

**Comment by agraubert** [comment]
1. Yes, I ran lima using the following settings: `lima --isoseq --dump-clips -j 24`
2. CCS was run with `--minPasses 0`. Specifically: `ccs --noPolish --minLength 3000 --maxLength 10000 --minPasses 0 --minZScore=-999 --maxDropFraction 0.8 --minPredictedAccuracy 0.8 --minSnr 3.75`
3. The primers I gave to lima are my best guess at what we used. I'm still trying to track down someone in my group who can tell me for sure

**Comment by Magdoll** [comment]
Hi @agraubert ,

The primer pair you provided looks correct to me as it is the Clontech SMARTer cDNA primer pair we officially recommend.

As Armin mentioned, the old Classify is more permissive and hence, has revealed on occasion, instances in which the cDNA library had too many TSO artifacts or incorrect library construction that were let through in the old Classify but revealed in the new LIMA. This may be the case. 

It'd be easiest if we can obtain one of the ccs.bam files that was used to run LIMA and compare with your `pbtranscript classify` result. If you are willing to share confidentially, please give me an email so you I can request for you to upload the data and we can take a look at it. 


--Liz

**Comment by agraubert** [comment]
It turns out it was a primer issue. It took a while, but I found someone who knew the primers used:

```
>F0_5p
TCGTCGGGGACAACTTTGTACAAAAAAGTTGGATGGGG
>R0_3p
GGGGACAACTTTGTACAAGAAAGTTGGGTTTT
>F1_5p
AAGCAGTGGTATCAACGCAGAGTACATGGGG
>R1_3p
AAGCAGTGGTATCAACGCAGAGTACTTTT
```

After running through lima, the F1-R1 primer set yields ~7000 transcripts, which is much more reasonable.  

Thanks for the help!
